library(dplyr)
library(openxlsx)
library(gplots)
library(ggplot2)
library(tibble)

create_boxplot <- function(results,scatter, filename) {
  directory <- "myapp/pictures/51_scattering_boxplots_RISK"
  filepath <- file.path(directory, filename)
  png(filepath, width = 200, height = 500)
  boxplot(results[[scatter]], data = results, main = "", xlab = "", ylab = "values", ylim = c(0, 100))
  
  # Berechnen und plotten Sie den Durchschnittswert
  mean_value <- mean(results[[scatter]])
  points(mean_value, col = "red", pch = 19)
  
  # Schließen Sie das PNG-Gerät
  dev.off()  
}


results <- read.csv(file = 'myapp/files/50_scattering/Streumaße.csv', header=TRUE) #importiere das answers file
results <- results %>% filter(scenario != "401" & scenario != "402" & scenario != "403")
results <- results %>% filter(type == "Risiko")
print (results)
results.classic.all <- results %>% filter(method == "classic" & group == "all")
results.graphiccentertogrid.all <- results %>% filter(method == "graphic center to grid" & group == "all")
results.graphiccenter.all <- results %>% filter(method == "graphic center" & group == "all")
results.graphicgridreached.all <- results %>% filter(method == "graphic grid reached" & group == "all")
results.graphicareas.all <- results %>% filter(method == "graphic areas" & group == "all")
results.weighted.all <- results %>% filter(method == "weighted" & group == "all")
results.pooling.all <- results %>% filter(method == "pooling " & group == "all")
print (results.weighted.all)
print (results.pooling.all)

results.classic.ct <- results %>% filter(method == "classic" & group == "core team")
results.graphiccentertogrid.ct <- results %>% filter(method == "graphic center to grid" & group == "core team")
results.graphiccenter.ct <- results %>% filter(method == "graphic center" & group == "core team")
results.graphicgridreached.ct <- results %>% filter(method == "graphic grid reached" & group == "core team")
results.graphicareas.ct <- results %>% filter(method == "graphic areas" & group == "core team")
results.weighted.ct <- results %>% filter(method == "weighted" & group == "core team")
results.pooling.ct <- results %>% filter(method == "pooling " & group == "core team")

results.classic.nct <- results %>% filter(method == "classic" & group == "non core team")
results.graphiccentertogrid.nct <- results %>% filter(method == "graphic center to grid" & group == "non core team")
results.graphiccenter.nct <- results %>% filter(method == "graphic center" & group == "non core team")
results.graphicgridreached.nct <- results %>% filter(method == "graphic grid reached" & group == "non core team")
results.graphicareas.nct <- results %>% filter(method == "graphic areas" & group == "non core team")
results.weighted.nct <- results %>% filter(method == "weighted" & group == "non core team")
results.pooling.nct <- results %>% filter(method == "pooling " & group == "non core team")



directory <- "myapp/pictures/51_scattering_boxplots_RISK"

#boxplot(results.classic.all$impact_FirstQuartile, data=results.classic.all , main = "", xlab = "", ylab = "values", ylim = c(0, 100))
#filename <- paste("OCCURRENCE_classic_range.png", sep = "")
#filepath <- file.path(directory, filename)
#png(filepath, width = 200, height = 500)
#boxplot(results.classic.all$occurrence_Range, data=results.classic.all , main = "", xlab = "", ylab = "values", ylim = c(0, 100))
#mean_value <- mean(results.classic.all$occurrence_Range)
#points(mean_value, col = "red", pch = 19)
#dev.off()  



create_boxplot(results.classic.all,"impact_Median","classic_IMPACT_median.png")
create_boxplot(results.classic.all,"impact_StandardDeviation","classic_IMPACT_sd.png")
create_boxplot(results.classic.all,"impact_Mean","classic_IMPACT_mean.png")
create_boxplot(results.classic.all,"impact_FirstQuartile","classic_IMPACT_firstQ.png")
create_boxplot(results.classic.all,"impact_ThirdQuartile","classic_IMPACT_thirdQ.png")
create_boxplot(results.classic.all,"impact_InterquartileRange","classic_IMPACT_IQR.png")
create_boxplot(results.classic.all,"impact_Minimum","classic_IMPACT_min.png")
create_boxplot(results.classic.all,"impact_Maximum","classic_IMPACT_max.png")
create_boxplot(results.classic.all,"impact_Range","classic_IMPACT_range.png")
create_boxplot(results.classic.all,"occurrence_Median","classic_OCCURRENCE_median.png")
create_boxplot(results.classic.all,"occurrence_StandardDeviation","classic_OCCURRENCE_sd.png")
create_boxplot(results.classic.all,"occurrence_Mean","classic_OCCURRENCE_mean.png")
create_boxplot(results.classic.all,"occurrence_FirstQuartile","classic_OCCURRENCE_firstQ.png")
create_boxplot(results.classic.all,"occurrence_ThirdQuartile","classic_OCCURRENCE_thirdQ.png")
create_boxplot(results.classic.all,"occurrence_InterquartileRange","classic_OCCURRENCE_IQR.png")
create_boxplot(results.classic.all,"occurrence_Minimum","classic_OCCURRENCE_min.png")
create_boxplot(results.classic.all,"occurrence_Maximum","classic_OCCURRENCE_max.png")
create_boxplot(results.classic.all,"occurrence_Range","classic_OCCURRENCE_range.png")

create_boxplot(results.graphiccentertogrid.all,"impact_Median","graphiccentertogrid_IMPACT_median.png")
create_boxplot(results.graphiccentertogrid.all,"impact_StandardDeviation","graphiccentertogrid_IMPACT_sd.png")
create_boxplot(results.graphiccentertogrid.all,"impact_Mean","graphiccentertogrid_IMPACT_mean.png")
create_boxplot(results.graphiccentertogrid.all,"impact_FirstQuartile","graphiccentertogrid_IMPACT_firstQ.png")
create_boxplot(results.graphiccentertogrid.all,"impact_ThirdQuartile","graphiccentertogrid_IMPACT_thirdQ.png")
create_boxplot(results.graphiccentertogrid.all,"impact_InterquartileRange","graphiccentertogrid_IMPACT_IQR.png")
create_boxplot(results.graphiccentertogrid.all,"impact_Minimum","graphiccentertogrid_IMPACT_min.png")
create_boxplot(results.graphiccentertogrid.all,"impact_Maximum","graphiccentertogrid_IMPACT_max.png")
create_boxplot(results.graphiccentertogrid.all,"impact_Range","graphiccentertogrid_IMPACT_range.png")
create_boxplot(results.graphiccentertogrid.all,"occurrence_Median","graphiccentertogrid_OCCURRENCE_median.png")
create_boxplot(results.graphiccentertogrid.all,"occurrence_StandardDeviation","graphiccentertogrid_OCCURRENCE_sd.png")
create_boxplot(results.graphiccentertogrid.all,"occurrence_Mean","graphiccentertogrid_OCCURRENCE_mean.png")
create_boxplot(results.graphiccentertogrid.all,"occurrence_FirstQuartile","graphiccentertogrid_OCCURRENCE_firstQ.png")
create_boxplot(results.graphiccentertogrid.all,"occurrence_ThirdQuartile","graphiccentertogrid_OCCURRENCE_thirdQ.png")
create_boxplot(results.graphiccentertogrid.all,"occurrence_InterquartileRange","graphiccentertogrid_OCCURRENCE_IQR.png")
create_boxplot(results.graphiccentertogrid.all,"occurrence_Minimum","graphiccentertogrid_OCCURRENCE_min.png")
create_boxplot(results.graphiccentertogrid.all,"occurrence_Maximum","graphiccentertogrid_OCCURRENCE_max.png")
create_boxplot(results.graphiccentertogrid.all,"occurrence_Range","graphiccentertogrid_OCCURRENCE_range.png")

create_boxplot(results.graphiccenter.all,"impact_Median","graphiccenter_IMPACT_median.png")
create_boxplot(results.graphiccenter.all,"impact_StandardDeviation","graphiccenter_IMPACT_sd.png")
create_boxplot(results.graphiccenter.all,"impact_Mean","graphiccenter_IMPACT_mean.png")
create_boxplot(results.graphiccenter.all,"impact_FirstQuartile","graphiccenter_IMPACT_firstQ.png")
create_boxplot(results.graphiccenter.all,"impact_ThirdQuartile","graphiccenter_IMPACT_thirdQ.png")
create_boxplot(results.graphiccenter.all,"impact_InterquartileRange","graphiccenter_IMPACT_IQR.png")
create_boxplot(results.graphiccenter.all,"impact_Minimum","graphiccenter_IMPACT_min.png")
create_boxplot(results.graphiccenter.all,"impact_Maximum","graphiccenter_IMPACT_max.png")
create_boxplot(results.graphiccenter.all,"impact_Range","graphiccenter_IMPACT_range.png")
create_boxplot(results.graphiccenter.all,"occurrence_Median","graphiccenter_OCCURRENCE_median.png")
create_boxplot(results.graphiccenter.all,"occurrence_StandardDeviation","graphiccenter_OCCURRENCE_sd.png")
create_boxplot(results.graphiccenter.all,"occurrence_Mean","graphiccenter_OCCURRENCE_mean.png")
create_boxplot(results.graphiccenter.all,"occurrence_FirstQuartile","graphiccenter_OCCURRENCE_firstQ.png")
create_boxplot(results.graphiccenter.all,"occurrence_ThirdQuartile","graphiccenter_OCCURRENCE_thirdQ.png")
create_boxplot(results.graphiccenter.all,"occurrence_InterquartileRange","graphiccenter_OCCURRENCE_IQR.png")
create_boxplot(results.graphiccenter.all,"occurrence_Minimum","graphiccenter_OCCURRENCE_min.png")
create_boxplot(results.graphiccenter.all,"occurrence_Maximum","graphiccenter_OCCURRENCE_max.png")
create_boxplot(results.graphiccenter.all,"occurrence_Range","graphiccenter_OCCURRENCE_range.png")

create_boxplot(results.graphicgridreached.all,"impact_Median","graphicgridreached_IMPACT_median.png")
create_boxplot(results.graphicgridreached.all,"impact_StandardDeviation","graphicgridreached_IMPACT_sd.png")
create_boxplot(results.graphicgridreached.all,"impact_Mean","graphicgridreached_IMPACT_mean.png")
create_boxplot(results.graphicgridreached.all,"impact_FirstQuartile","graphicgridreached_IMPACT_firstQ.png")
create_boxplot(results.graphicgridreached.all,"impact_ThirdQuartile","graphicgridreached_IMPACT_thirdQ.png")
create_boxplot(results.graphicgridreached.all,"impact_InterquartileRange","graphicgridreached_IMPACT_IQR.png")
create_boxplot(results.graphicgridreached.all,"impact_Minimum","graphicgridreached_IMPACT_min.png")
create_boxplot(results.graphicgridreached.all,"impact_Maximum","graphicgridreached_IMPACT_max.png")
create_boxplot(results.graphicgridreached.all,"impact_Range","graphicgridreached_IMPACT_range.png")
create_boxplot(results.graphicgridreached.all,"occurrence_Median","graphicgridreached_OCCURRENCE_median.png")
create_boxplot(results.graphicgridreached.all,"occurrence_StandardDeviation","graphicgridreached_OCCURRENCE_sd.png")
create_boxplot(results.graphicgridreached.all,"occurrence_Mean","graphicgridreached_OCCURRENCE_mean.png")
create_boxplot(results.graphicgridreached.all,"occurrence_FirstQuartile","graphicgridreached_OCCURRENCE_firstQ.png")
create_boxplot(results.graphicgridreached.all,"occurrence_ThirdQuartile","graphicgridreached_OCCURRENCE_thirdQ.png")
create_boxplot(results.graphicgridreached.all,"occurrence_InterquartileRange","graphicgridreached_OCCURRENCE_IQR.png")
create_boxplot(results.graphicgridreached.all,"occurrence_Minimum","graphicgridreached_OCCURRENCE_min.png")
create_boxplot(results.graphicgridreached.all,"occurrence_Maximum","graphicgridreached_OCCURRENCE_max.png")
create_boxplot(results.graphicgridreached.all,"occurrence_Range","graphicgridreached_OCCURRENCE_range.png")

create_boxplot(results.graphicareas.all,"impact_Median","graphicareas_IMPACT_median.png")
create_boxplot(results.graphicareas.all,"impact_StandardDeviation","graphicareas_IMPACT_sd.png")
create_boxplot(results.graphicareas.all,"impact_Mean","graphicareas_IMPACT_mean.png")
create_boxplot(results.graphicareas.all,"impact_FirstQuartile","graphicareas_IMPACT_firstQ.png")
create_boxplot(results.graphicareas.all,"impact_ThirdQuartile","graphicareas_IMPACT_thirdQ.png")
create_boxplot(results.graphicareas.all,"impact_InterquartileRange","graphicareas_IMPACT_IQR.png")
create_boxplot(results.graphicareas.all,"impact_Minimum","graphicareas_IMPACT_min.png")
create_boxplot(results.graphicareas.all,"impact_Maximum","graphicareas_IMPACT_max.png")
create_boxplot(results.graphicareas.all,"impact_Range","graphicareas_IMPACT_range.png")
create_boxplot(results.graphicareas.all,"occurrence_Median","graphicareas_OCCURRENCE_median.png")
create_boxplot(results.graphicareas.all,"occurrence_StandardDeviation","graphicareas_OCCURRENCE_sd.png")
create_boxplot(results.graphicareas.all,"occurrence_Mean","graphicareas_OCCURRENCE_mean.png")
create_boxplot(results.graphicareas.all,"occurrence_FirstQuartile","graphicareas_OCCURRENCE_firstQ.png")
create_boxplot(results.graphicareas.all,"occurrence_ThirdQuartile","graphicareas_OCCURRENCE_thirdQ.png")
create_boxplot(results.graphicareas.all,"occurrence_InterquartileRange","graphicareas_OCCURRENCE_IQR.png")
create_boxplot(results.graphicareas.all,"occurrence_Minimum","graphicareas_OCCURRENCE_min.png")
create_boxplot(results.graphicareas.all,"occurrence_Maximum","graphicareas_OCCURRENCE_max.png")
create_boxplot(results.graphicareas.all,"occurrence_Range","graphicareas_OCCURRENCE_range.png")

create_boxplot(results.weighted.all,"impact_Median","weighted_IMPACT_median.png")
create_boxplot(results.weighted.all,"impact_StandardDeviation","weighted_IMPACT_sd.png")
create_boxplot(results.weighted.all,"impact_Mean","weighted_IMPACT_mean.png")
create_boxplot(results.weighted.all,"impact_FirstQuartile","weighted_IMPACT_firstQ.png")
create_boxplot(results.weighted.all,"impact_ThirdQuartile","weighted_IMPACT_thirdQ.png")
create_boxplot(results.weighted.all,"impact_InterquartileRange","weighted_IMPACT_IQR.png")
create_boxplot(results.weighted.all,"impact_Minimum","weighted_IMPACT_min.png")
create_boxplot(results.weighted.all,"impact_Maximum","weighted_IMPACT_max.png")
create_boxplot(results.weighted.all,"impact_Range","weighted_IMPACT_range.png")
create_boxplot(results.weighted.all,"occurrence_Median","weighted_OCCURRENCE_median.png")
create_boxplot(results.weighted.all,"occurrence_StandardDeviation","weighted_OCCURRENCE_sd.png")
create_boxplot(results.weighted.all,"occurrence_Mean","weighted_OCCURRENCE_mean.png")
create_boxplot(results.weighted.all,"occurrence_FirstQuartile","weighted_OCCURRENCE_firstQ.png")
create_boxplot(results.weighted.all,"occurrence_ThirdQuartile","weighted_OCCURRENCE_thirdQ.png")
create_boxplot(results.weighted.all,"occurrence_InterquartileRange","weighted_OCCURRENCE_IQR.png")
create_boxplot(results.weighted.all,"occurrence_Minimum","weighted_OCCURRENCE_min.png")
create_boxplot(results.weighted.all,"occurrence_Maximum","weighted_OCCURRENCE_max.png")
create_boxplot(results.weighted.all,"occurrence_Range","weighted_OCCURRENCE_range.png")

create_boxplot(results.pooling.all,"impact_Median","pooling_IMPACT_median.png")
create_boxplot(results.pooling.all,"impact_StandardDeviation","pooling_IMPACT_sd.png")
create_boxplot(results.pooling.all,"impact_Mean","pooling_IMPACT_mean.png")
create_boxplot(results.pooling.all,"impact_FirstQuartile","pooling_IMPACT_firstQ.png")
create_boxplot(results.pooling.all,"impact_ThirdQuartile","pooling_IMPACT_thirdQ.png")
create_boxplot(results.pooling.all,"impact_InterquartileRange","pooling_IMPACT_IQR.png")
create_boxplot(results.pooling.all,"impact_Minimum","pooling_IMPACT_min.png")
create_boxplot(results.pooling.all,"impact_Maximum","pooling_IMPACT_max.png")
create_boxplot(results.pooling.all,"impact_Range","pooling_IMPACT_range.png")
create_boxplot(results.pooling.all,"occurrence_Median","pooling_OCCURRENCE_median.png")
create_boxplot(results.pooling.all,"occurrence_StandardDeviation","pooling_OCCURRENCE_sd.png")
create_boxplot(results.pooling.all,"occurrence_Mean","pooling_OCCURRENCE_mean.png")
create_boxplot(results.pooling.all,"occurrence_FirstQuartile","pooling_OCCURRENCE_firstQ.png")
create_boxplot(results.pooling.all,"occurrence_ThirdQuartile","pooling_OCCURRENCE_thirdQ.png")
create_boxplot(results.pooling.all,"occurrence_InterquartileRange","pooling_OCCURRENCE_IQR.png")
create_boxplot(results.pooling.all,"occurrence_Minimum","pooling_OCCURRENCE_min.png")
create_boxplot(results.pooling.all,"occurrence_Maximum","pooling_OCCURRENCE_max.png")
create_boxplot(results.pooling.all,"occurrence_Range","pooling_OCCURRENCE_range.png")

##### CORE TEAM ##############
create_boxplot(results.classic.ct,"impact_Median","classic_IMPACT_median_ct.png")
create_boxplot(results.classic.ct,"impact_StandardDeviation","classic_IMPACT_sd_ct.png")
create_boxplot(results.classic.ct,"impact_Mean","classic_IMPACT_mean_ct.png")
create_boxplot(results.classic.ct,"impact_FirstQuartile","classic_IMPACT_firstQ_ct.png")
create_boxplot(results.classic.ct,"impact_ThirdQuartile","classic_IMPACT_thirdQ_ct.png")
create_boxplot(results.classic.ct,"impact_InterquartileRange","classic_IMPACT_IQR_ct.png")
create_boxplot(results.classic.ct,"impact_Minimum","classic_IMPACT_min_ct.png")
create_boxplot(results.classic.ct,"impact_Maximum","classic_IMPACT_max_ct.png")
create_boxplot(results.classic.ct,"impact_Range","classic_IMPACT_range_ct.png")
create_boxplot(results.classic.ct,"occurrence_Median","classic_OCCURRENCE_median_ct.png")
create_boxplot(results.classic.ct,"occurrence_StandardDeviation","classic_OCCURRENCE_sd_ct.png")
create_boxplot(results.classic.ct,"occurrence_Mean","classic_OCCURRENCE_mean_ct.png")
create_boxplot(results.classic.ct,"occurrence_FirstQuartile","classic_OCCURRENCE_firstQ_ct.png")
create_boxplot(results.classic.ct,"occurrence_ThirdQuartile","classic_OCCURRENCE_thirdQ_ct.png")
create_boxplot(results.classic.ct,"occurrence_InterquartileRange","classic_OCCURRENCE_IQR_ct.png")
create_boxplot(results.classic.ct,"occurrence_Minimum","classic_OCCURRENCE_min_ct.png")
create_boxplot(results.classic.ct,"occurrence_Maximum","classic_OCCURRENCE_max_ct.png")
create_boxplot(results.classic.ct,"occurrence_Range","classic_OCCURRENCE_range_ct.png")

create_boxplot(results.graphiccentertogrid.ct,"impact_Median","graphiccentertogrid_IMPACT_median_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"impact_StandardDeviation","graphiccentertogrid_IMPACT_sd_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"impact_Mean","graphiccentertogrid_IMPACT_mean_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"impact_FirstQuartile","graphiccentertogrid_IMPACT_firstQ_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"impact_ThirdQuartile","graphiccentertogrid_IMPACT_thirdQ_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"impact_InterquartileRange","graphiccentertogrid_IMPACT_IQR_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"impact_Minimum","graphiccentertogrid_IMPACT_min_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"impact_Maximum","graphiccentertogrid_IMPACT_max_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"impact_Range","graphiccentertogrid_IMPACT_range_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"occurrence_Median","graphiccentertogrid_OCCURRENCE_median_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"occurrence_StandardDeviation","graphiccentertogrid_OCCURRENCE_sd_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"occurrence_Mean","graphiccentertogrid_OCCURRENCE_mean_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"occurrence_FirstQuartile","graphiccentertogrid_OCCURRENCE_firstQ_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"occurrence_ThirdQuartile","graphiccentertogrid_OCCURRENCE_thirdQ_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"occurrence_InterquartileRange","graphiccentertogrid_OCCURRENCE_IQR_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"occurrence_Minimum","graphiccentertogrid_OCCURRENCE_min_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"occurrence_Maximum","graphiccentertogrid_OCCURRENCE_max_ct.png")
create_boxplot(results.graphiccentertogrid.ct,"occurrence_Range","graphiccentertogrid_OCCURRENCE_range_ct.png")

create_boxplot(results.graphiccenter.ct,"impact_Median","graphiccenter_IMPACT_median_ct.png")
create_boxplot(results.graphiccenter.ct,"impact_StandardDeviation","graphiccenter_IMPACT_sd_ct.png")
create_boxplot(results.graphiccenter.ct,"impact_Mean","graphiccenter_IMPACT_mean_ct.png")
create_boxplot(results.graphiccenter.ct,"impact_FirstQuartile","graphiccenter_IMPACT_firstQ_ct.png")
create_boxplot(results.graphiccenter.ct,"impact_ThirdQuartile","graphiccenter_IMPACT_thirdQ_ct.png")
create_boxplot(results.graphiccenter.ct,"impact_InterquartileRange","graphiccenter_IMPACT_IQR_ct.png")
create_boxplot(results.graphiccenter.ct,"impact_Minimum","graphiccenter_IMPACT_min_ct.png")
create_boxplot(results.graphiccenter.ct,"impact_Maximum","graphiccenter_IMPACT_max_ct.png")
create_boxplot(results.graphiccenter.ct,"impact_Range","graphiccenter_IMPACT_range_ct.png")
create_boxplot(results.graphiccenter.ct,"occurrence_Median","graphiccenter_OCCURRENCE_median_ct.png")
create_boxplot(results.graphiccenter.ct,"occurrence_StandardDeviation","graphiccenter_OCCURRENCE_sd_ct.png")
create_boxplot(results.graphiccenter.ct,"occurrence_Mean","graphiccenter_OCCURRENCE_mean_ct.png")
create_boxplot(results.graphiccenter.ct,"occurrence_FirstQuartile","graphiccenter_OCCURRENCE_firstQ_ct.png")
create_boxplot(results.graphiccenter.ct,"occurrence_ThirdQuartile","graphiccenter_OCCURRENCE_thirdQ_ct.png")
create_boxplot(results.graphiccenter.ct,"occurrence_InterquartileRange","graphiccenter_OCCURRENCE_IQR_ct.png")
create_boxplot(results.graphiccenter.ct,"occurrence_Minimum","graphiccenter_OCCURRENCE_min_ct.png")
create_boxplot(results.graphiccenter.ct,"occurrence_Maximum","graphiccenter_OCCURRENCE_max_ct.png")
create_boxplot(results.graphiccenter.ct,"occurrence_Range","graphiccenter_OCCURRENCE_range_ct.png")

create_boxplot(results.graphicgridreached.ct,"impact_Median","graphicgridreached_IMPACT_median_ct.png")
create_boxplot(results.graphicgridreached.ct,"impact_StandardDeviation","graphicgridreached_IMPACT_sd_ct.png")
create_boxplot(results.graphicgridreached.ct,"impact_Mean","graphicgridreached_IMPACT_mean_ct.png")
create_boxplot(results.graphicgridreached.ct,"impact_FirstQuartile","graphicgridreached_IMPACT_firstQ_ct.png")
create_boxplot(results.graphicgridreached.ct,"impact_ThirdQuartile","graphicgridreached_IMPACT_thirdQ_ct.png")
create_boxplot(results.graphicgridreached.ct,"impact_InterquartileRange","graphicgridreached_IMPACT_IQR_ct.png")
create_boxplot(results.graphicgridreached.ct,"impact_Minimum","graphicgridreached_IMPACT_min_ct.png")
create_boxplot(results.graphicgridreached.ct,"impact_Maximum","graphicgridreached_IMPACT_max_ct.png")
create_boxplot(results.graphicgridreached.ct,"impact_Range","graphicgridreached_IMPACT_range_ct.png")
create_boxplot(results.graphicgridreached.ct,"occurrence_Median","graphicgridreached_OCCURRENCE_median_ct.png")
create_boxplot(results.graphicgridreached.ct,"occurrence_StandardDeviation","graphicgridreached_OCCURRENCE_sd_ct.png")
create_boxplot(results.graphicgridreached.ct,"occurrence_Mean","graphicgridreached_OCCURRENCE_mean_ct.png")
create_boxplot(results.graphicgridreached.ct,"occurrence_FirstQuartile","graphicgridreached_OCCURRENCE_firstQ_ct.png")
create_boxplot(results.graphicgridreached.ct,"occurrence_ThirdQuartile","graphicgridreached_OCCURRENCE_thirdQ_ct.png")
create_boxplot(results.graphicgridreached.ct,"occurrence_InterquartileRange","graphicgridreached_OCCURRENCE_IQR_ct.png")
create_boxplot(results.graphicgridreached.ct,"occurrence_Minimum","graphicgridreached_OCCURRENCE_min_ct.png")
create_boxplot(results.graphicgridreached.ct,"occurrence_Maximum","graphicgridreached_OCCURRENCE_max_ct.png")
create_boxplot(results.graphicgridreached.ct,"occurrence_Range","graphicgridreached_OCCURRENCE_range_ct.png")

create_boxplot(results.graphicareas.ct,"impact_Median","graphicareas_IMPACT_median_ct.png")
create_boxplot(results.graphicareas.ct,"impact_StandardDeviation","graphicareas_IMPACT_sd_ct.png")
create_boxplot(results.graphicareas.ct,"impact_Mean","graphicareas_IMPACT_mean_ct.png")
create_boxplot(results.graphicareas.ct,"impact_FirstQuartile","graphicareas_IMPACT_firstQ_ct.png")
create_boxplot(results.graphicareas.ct,"impact_ThirdQuartile","graphicareas_IMPACT_thirdQ_ct.png")
create_boxplot(results.graphicareas.ct,"impact_InterquartileRange","graphicareas_IMPACT_IQR_ct.png")
create_boxplot(results.graphicareas.ct,"impact_Minimum","graphicareas_IMPACT_min_ct.png")
create_boxplot(results.graphicareas.ct,"impact_Maximum","graphicareas_IMPACT_max_ct.png")
create_boxplot(results.graphicareas.ct,"impact_Range","graphicareas_IMPACT_range_ct.png")
create_boxplot(results.graphicareas.ct,"occurrence_Median","graphicareas_OCCURRENCE_median_ct.png")
create_boxplot(results.graphicareas.ct,"occurrence_StandardDeviation","graphicareas_OCCURRENCE_sd_ct.png")
create_boxplot(results.graphicareas.ct,"occurrence_Mean","graphicareas_OCCURRENCE_mean_ct.png")
create_boxplot(results.graphicareas.ct,"occurrence_FirstQuartile","graphicareas_OCCURRENCE_firstQ_ct.png")
create_boxplot(results.graphicareas.ct,"occurrence_ThirdQuartile","graphicareas_OCCURRENCE_thirdQ_ct.png")
create_boxplot(results.graphicareas.ct,"occurrence_InterquartileRange","graphicareas_OCCURRENCE_IQR_ct.png")
create_boxplot(results.graphicareas.ct,"occurrence_Minimum","graphicareas_OCCURRENCE_min_ct.png")
create_boxplot(results.graphicareas.ct,"occurrence_Maximum","graphicareas_OCCURRENCE_max_ct.png")
create_boxplot(results.graphicareas.ct,"occurrence_Range","graphicareas_OCCURRENCE_range_ct.png")

create_boxplot(results.weighted.ct,"impact_Median","weighted_IMPACT_median_ct.png")
create_boxplot(results.weighted.ct,"impact_StandardDeviation","weighted_IMPACT_sd_ct.png")
create_boxplot(results.weighted.ct,"impact_Mean","weighted_IMPACT_mean_ct.png")
create_boxplot(results.weighted.ct,"impact_FirstQuartile","weighted_IMPACT_firstQ_ct.png")
create_boxplot(results.weighted.ct,"impact_ThirdQuartile","weighted_IMPACT_thirdQ_ct.png")
create_boxplot(results.weighted.ct,"impact_InterquartileRange","weighted_IMPACT_IQR_ct.png")
create_boxplot(results.weighted.ct,"impact_Minimum","weighted_IMPACT_min_ct.png")
create_boxplot(results.weighted.ct,"impact_Maximum","weighted_IMPACT_max_ct.png")
create_boxplot(results.weighted.ct,"impact_Range","weighted_IMPACT_range_ct.png")
create_boxplot(results.weighted.ct,"occurrence_Median","weighted_OCCURRENCE_median_ct.png")
create_boxplot(results.weighted.ct,"occurrence_StandardDeviation","weighted_OCCURRENCE_sd_ct.png")
create_boxplot(results.weighted.ct,"occurrence_Mean","weighted_OCCURRENCE_mean_ct.png")
create_boxplot(results.weighted.ct,"occurrence_FirstQuartile","weighted_OCCURRENCE_firstQ_ct.png")
create_boxplot(results.weighted.ct,"occurrence_ThirdQuartile","weighted_OCCURRENCE_thirdQ_ct.png")
create_boxplot(results.weighted.ct,"occurrence_InterquartileRange","weighted_OCCURRENCE_IQR_ct.png")
create_boxplot(results.weighted.ct,"occurrence_Minimum","weighted_OCCURRENCE_min_ct.png")
create_boxplot(results.weighted.ct,"occurrence_Maximum","weighted_OCCURRENCE_max_ct.png")
create_boxplot(results.weighted.ct,"occurrence_Range","weighted_OCCURRENCE_range_ct.png")

create_boxplot(results.pooling.ct,"impact_Median","pooling_IMPACT_median_ct.png")
create_boxplot(results.pooling.ct,"impact_StandardDeviation","pooling_IMPACT_sd_ct.png")
create_boxplot(results.pooling.ct,"impact_Mean","pooling_IMPACT_mean_ct.png")
create_boxplot(results.pooling.ct,"impact_FirstQuartile","pooling_IMPACT_firstQ_ct.png")
create_boxplot(results.pooling.ct,"impact_ThirdQuartile","pooling_IMPACT_thirdQ_ct.png")
create_boxplot(results.pooling.ct,"impact_InterquartileRange","pooling_IMPACT_IQR_ct.png")
create_boxplot(results.pooling.ct,"impact_Minimum","pooling_IMPACT_min_ct.png")
create_boxplot(results.pooling.ct,"impact_Maximum","pooling_IMPACT_max_ct.png")
create_boxplot(results.pooling.ct,"impact_Range","pooling_IMPACT_range_ct.png")
create_boxplot(results.pooling.ct,"occurrence_Median","pooling_OCCURRENCE_median_ct.png")
create_boxplot(results.pooling.ct,"occurrence_StandardDeviation","pooling_OCCURRENCE_sd_ct.png")
create_boxplot(results.pooling.ct,"occurrence_Mean","pooling_OCCURRENCE_mean_ct.png")
create_boxplot(results.pooling.ct,"occurrence_FirstQuartile","pooling_OCCURRENCE_firstQ_ct.png")
create_boxplot(results.pooling.ct,"occurrence_ThirdQuartile","pooling_OCCURRENCE_thirdQ_ct.png")
create_boxplot(results.pooling.ct,"occurrence_InterquartileRange","pooling_OCCURRENCE_IQR_ct.png")
create_boxplot(results.pooling.ct,"occurrence_Minimum","pooling_OCCURRENCE_min_ct.png")
create_boxplot(results.pooling.ct,"occurrence_Maximum","pooling_OCCURRENCE_max_ct.png")
create_boxplot(results.pooling.ct,"occurrence_Range","pooling_OCCURRENCE_range_ct.png")


##### NONE CORE TEAM ##############


create_boxplot(results.classic.nct,"impact_Median","classic_IMPACT_median_nct.png")
create_boxplot(results.classic.nct,"impact_StandardDeviation","classic_IMPACT_sd_nct.png")
create_boxplot(results.classic.nct,"impact_Mean","classic_IMPACT_mean_nct.png")
create_boxplot(results.classic.nct,"impact_FirstQuartile","classic_IMPACT_firstQ_nct.png")
create_boxplot(results.classic.nct,"impact_ThirdQuartile","classic_IMPACT_thirdQ_nct.png")
create_boxplot(results.classic.nct,"impact_InterquartileRange","classic_IMPACT_IQR_nct.png")
create_boxplot(results.classic.nct,"impact_Minimum","classic_IMPACT_min_nct.png")
create_boxplot(results.classic.nct,"impact_Maximum","classic_IMPACT_max_nct.png")
create_boxplot(results.classic.nct,"impact_Range","classic_IMPACT_range_nct.png")
create_boxplot(results.classic.nct,"occurrence_Median","classic_OCCURRENCE_median_nct.png")
create_boxplot(results.classic.nct,"occurrence_StandardDeviation","classic_OCCURRENCE_sd_nct.png")
create_boxplot(results.classic.nct,"occurrence_Mean","classic_OCCURRENCE_mean_nct.png")
create_boxplot(results.classic.nct,"occurrence_FirstQuartile","classic_OCCURRENCE_firstQ_nct.png")
create_boxplot(results.classic.nct,"occurrence_ThirdQuartile","classic_OCCURRENCE_thirdQ_nct.png")
create_boxplot(results.classic.nct,"occurrence_InterquartileRange","classic_OCCURRENCE_IQR_nct.png")
create_boxplot(results.classic.nct,"occurrence_Minimum","classic_OCCURRENCE_min_nct.png")
create_boxplot(results.classic.nct,"occurrence_Maximum","classic_OCCURRENCE_max_nct.png")
create_boxplot(results.classic.nct,"occurrence_Range","classic_OCCURRENCE_range_nct.png")

create_boxplot(results.graphiccentertogrid.nct,"impact_Median","graphiccentertogrid_IMPACT_median_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"impact_StandardDeviation","graphiccentertogrid_IMPACT_sd_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"impact_Mean","graphiccentertogrid_IMPACT_mean_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"impact_FirstQuartile","graphiccentertogrid_IMPACT_firstQ_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"impact_ThirdQuartile","graphiccentertogrid_IMPACT_thirdQ_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"impact_InterquartileRange","graphiccentertogrid_IMPACT_IQR_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"impact_Minimum","graphiccentertogrid_IMPACT_min_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"impact_Maximum","graphiccentertogrid_IMPACT_max_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"impact_Range","graphiccentertogrid_IMPACT_range_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"occurrence_Median","graphiccentertogrid_OCCURRENCE_median_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"occurrence_StandardDeviation","graphiccentertogrid_OCCURRENCE_sd_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"occurrence_Mean","graphiccentertogrid_OCCURRENCE_mean_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"occurrence_FirstQuartile","graphiccentertogrid_OCCURRENCE_firstQ_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"occurrence_ThirdQuartile","graphiccentertogrid_OCCURRENCE_thirdQ_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"occurrence_InterquartileRange","graphiccentertogrid_OCCURRENCE_IQR_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"occurrence_Minimum","graphiccentertogrid_OCCURRENCE_min_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"occurrence_Maximum","graphiccentertogrid_OCCURRENCE_max_nct.png")
create_boxplot(results.graphiccentertogrid.nct,"occurrence_Range","graphiccentertogrid_OCCURRENCE_range_nct.png")

create_boxplot(results.graphiccenter.nct,"impact_Median","graphiccenter_IMPACT_median_nct.png")
create_boxplot(results.graphiccenter.nct,"impact_StandardDeviation","graphiccenter_IMPACT_sd_nct.png")
create_boxplot(results.graphiccenter.nct,"impact_Mean","graphiccenter_IMPACT_mean_nct.png")
create_boxplot(results.graphiccenter.nct,"impact_FirstQuartile","graphiccenter_IMPACT_firstQ_nct.png")
create_boxplot(results.graphiccenter.nct,"impact_ThirdQuartile","graphiccenter_IMPACT_thirdQ_nct.png")
create_boxplot(results.graphiccenter.nct,"impact_InterquartileRange","graphiccenter_IMPACT_IQR_nct.png")
create_boxplot(results.graphiccenter.nct,"impact_Minimum","graphiccenter_IMPACT_min_nct.png")
create_boxplot(results.graphiccenter.nct,"impact_Maximum","graphiccenter_IMPACT_max_nct.png")
create_boxplot(results.graphiccenter.nct,"impact_Range","graphiccenter_IMPACT_range_nct.png")
create_boxplot(results.graphiccenter.nct,"occurrence_Median","graphiccenter_OCCURRENCE_median_nct.png")
create_boxplot(results.graphiccenter.nct,"occurrence_StandardDeviation","graphiccenter_OCCURRENCE_sd_nct.png")
create_boxplot(results.graphiccenter.nct,"occurrence_Mean","graphiccenter_OCCURRENCE_mean_nct.png")
create_boxplot(results.graphiccenter.nct,"occurrence_FirstQuartile","graphiccenter_OCCURRENCE_firstQ_nct.png")
create_boxplot(results.graphiccenter.nct,"occurrence_ThirdQuartile","graphiccenter_OCCURRENCE_thirdQ_nct.png")
create_boxplot(results.graphiccenter.nct,"occurrence_InterquartileRange","graphiccenter_OCCURRENCE_IQR_nct.png")
create_boxplot(results.graphiccenter.nct,"occurrence_Minimum","graphiccenter_OCCURRENCE_min_nct.png")
create_boxplot(results.graphiccenter.nct,"occurrence_Maximum","graphiccenter_OCCURRENCE_max_nct.png")
create_boxplot(results.graphiccenter.nct,"occurrence_Range","graphiccenter_OCCURRENCE_range_nct.png")

create_boxplot(results.graphicgridreached.nct,"impact_Median","graphicgridreached_IMPACT_median_nct.png")
create_boxplot(results.graphicgridreached.nct,"impact_StandardDeviation","graphicgridreached_IMPACT_sd_nct.png")
create_boxplot(results.graphicgridreached.nct,"impact_Mean","graphicgridreached_IMPACT_mean_nct.png")
create_boxplot(results.graphicgridreached.nct,"impact_FirstQuartile","graphicgridreached_IMPACT_firstQ_nct.png")
create_boxplot(results.graphicgridreached.nct,"impact_ThirdQuartile","graphicgridreached_IMPACT_thirdQ_nct.png")
create_boxplot(results.graphicgridreached.nct,"impact_InterquartileRange","graphicgridreached_IMPACT_IQR_nct.png")
create_boxplot(results.graphicgridreached.nct,"impact_Minimum","graphicgridreached_IMPACT_min_nct.png")
create_boxplot(results.graphicgridreached.nct,"impact_Maximum","graphicgridreached_IMPACT_max_nct.png")
create_boxplot(results.graphicgridreached.nct,"impact_Range","graphicgridreached_IMPACT_range_nct.png")
create_boxplot(results.graphicgridreached.nct,"occurrence_Median","graphicgridreached_OCCURRENCE_median_nct.png")
create_boxplot(results.graphicgridreached.nct,"occurrence_StandardDeviation","graphicgridreached_OCCURRENCE_sd_nct.png")
create_boxplot(results.graphicgridreached.nct,"occurrence_Mean","graphicgridreached_OCCURRENCE_mean_nct.png")
create_boxplot(results.graphicgridreached.nct,"occurrence_FirstQuartile","graphicgridreached_OCCURRENCE_firstQ_nct.png")
create_boxplot(results.graphicgridreached.nct,"occurrence_ThirdQuartile","graphicgridreached_OCCURRENCE_thirdQ_nct.png")
create_boxplot(results.graphicgridreached.nct,"occurrence_InterquartileRange","graphicgridreached_OCCURRENCE_IQR_nct.png")
create_boxplot(results.graphicgridreached.nct,"occurrence_Minimum","graphicgridreached_OCCURRENCE_min_nct.png")
create_boxplot(results.graphicgridreached.nct,"occurrence_Maximum","graphicgridreached_OCCURRENCE_max_nct.png")
create_boxplot(results.graphicgridreached.nct,"occurrence_Range","graphicgridreached_OCCURRENCE_range_nct.png")

create_boxplot(results.graphicareas.nct,"impact_Median","graphicareas_IMPACT_median_nct.png")
create_boxplot(results.graphicareas.nct,"impact_StandardDeviation","graphicareas_IMPACT_sd_nct.png")
create_boxplot(results.graphicareas.nct,"impact_Mean","graphicareas_IMPACT_mean_nct.png")
create_boxplot(results.graphicareas.nct,"impact_FirstQuartile","graphicareas_IMPACT_firstQ_nct.png")
create_boxplot(results.graphicareas.nct,"impact_ThirdQuartile","graphicareas_IMPACT_thirdQ_nct.png")
create_boxplot(results.graphicareas.nct,"impact_InterquartileRange","graphicareas_IMPACT_IQR_nct.png")
create_boxplot(results.graphicareas.nct,"impact_Minimum","graphicareas_IMPACT_min_nct.png")
create_boxplot(results.graphicareas.nct,"impact_Maximum","graphicareas_IMPACT_max_nct.png")
create_boxplot(results.graphicareas.nct,"impact_Range","graphicareas_IMPACT_range_nct.png")
create_boxplot(results.graphicareas.nct,"occurrence_Median","graphicareas_OCCURRENCE_median_nct.png")
create_boxplot(results.graphicareas.nct,"occurrence_StandardDeviation","graphicareas_OCCURRENCE_sd_nct.png")
create_boxplot(results.graphicareas.nct,"occurrence_Mean","graphicareas_OCCURRENCE_mean_nct.png")
create_boxplot(results.graphicareas.nct,"occurrence_FirstQuartile","graphicareas_OCCURRENCE_firstQ_nct.png")
create_boxplot(results.graphicareas.nct,"occurrence_ThirdQuartile","graphicareas_OCCURRENCE_thirdQ_nct.png")
create_boxplot(results.graphicareas.nct,"occurrence_InterquartileRange","graphicareas_OCCURRENCE_IQR_nct.png")
create_boxplot(results.graphicareas.nct,"occurrence_Minimum","graphicareas_OCCURRENCE_min_nct.png")
create_boxplot(results.graphicareas.nct,"occurrence_Maximum","graphicareas_OCCURRENCE_max_nct.png")
create_boxplot(results.graphicareas.nct,"occurrence_Range","graphicareas_OCCURRENCE_range_nct.png")

create_boxplot(results.weighted.nct,"impact_Median","weighted_IMPACT_median_nct.png")
create_boxplot(results.weighted.nct,"impact_StandardDeviation","weighted_IMPACT_sd_nct.png")
create_boxplot(results.weighted.nct,"impact_Mean","weighted_IMPACT_mean_nct.png")
create_boxplot(results.weighted.nct,"impact_FirstQuartile","weighted_IMPACT_firstQ_nct.png")
create_boxplot(results.weighted.nct,"impact_ThirdQuartile","weighted_IMPACT_thirdQ_nct.png")
create_boxplot(results.weighted.nct,"impact_InterquartileRange","weighted_IMPACT_IQR_nct.png")
create_boxplot(results.weighted.nct,"impact_Minimum","weighted_IMPACT_min_nct.png")
create_boxplot(results.weighted.nct,"impact_Maximum","weighted_IMPACT_max_nct.png")
create_boxplot(results.weighted.nct,"impact_Range","weighted_IMPACT_range_nct.png")
create_boxplot(results.weighted.nct,"occurrence_Median","weighted_OCCURRENCE_median_nct.png")
create_boxplot(results.weighted.nct,"occurrence_StandardDeviation","weighted_OCCURRENCE_sd_nct.png")
create_boxplot(results.weighted.nct,"occurrence_Mean","weighted_OCCURRENCE_mean_nct.png")
create_boxplot(results.weighted.nct,"occurrence_FirstQuartile","weighted_OCCURRENCE_firstQ_nct.png")
create_boxplot(results.weighted.nct,"occurrence_ThirdQuartile","weighted_OCCURRENCE_thirdQ_nct.png")
create_boxplot(results.weighted.nct,"occurrence_InterquartileRange","weighted_OCCURRENCE_IQR_nct.png")
create_boxplot(results.weighted.nct,"occurrence_Minimum","weighted_OCCURRENCE_min_nct.png")
create_boxplot(results.weighted.nct,"occurrence_Maximum","weighted_OCCURRENCE_max_nct.png")
create_boxplot(results.weighted.nct,"occurrence_Range","weighted_OCCURRENCE_range_nct.png")

create_boxplot(results.pooling.nct,"impact_Median","pooling_IMPACT_median_nct.png")
create_boxplot(results.pooling.nct,"impact_StandardDeviation","pooling_IMPACT_sd_nct.png")
create_boxplot(results.pooling.nct,"impact_Mean","pooling_IMPACT_mean_nct.png")
create_boxplot(results.pooling.nct,"impact_FirstQuartile","pooling_IMPACT_firstQ_nct.png")
create_boxplot(results.pooling.nct,"impact_ThirdQuartile","pooling_IMPACT_thirdQ_nct.png")
create_boxplot(results.pooling.nct,"impact_InterquartileRange","pooling_IMPACT_IQR_nct.png")
create_boxplot(results.pooling.nct,"impact_Minimum","pooling_IMPACT_min_nct.png")
create_boxplot(results.pooling.nct,"impact_Maximum","pooling_IMPACT_max_nct.png")
create_boxplot(results.pooling.nct,"impact_Range","pooling_IMPACT_range_nct.png")
create_boxplot(results.pooling.nct,"occurrence_Median","pooling_OCCURRENCE_median_nct.png")
create_boxplot(results.pooling.nct,"occurrence_StandardDeviation","pooling_OCCURRENCE_sd_nct.png")
create_boxplot(results.pooling.nct,"occurrence_Mean","pooling_OCCURRENCE_mean_nct.png")
create_boxplot(results.pooling.nct,"occurrence_FirstQuartile","pooling_OCCURRENCE_firstQ_nct.png")
create_boxplot(results.pooling.nct,"occurrence_ThirdQuartile","pooling_OCCURRENCE_thirdQ_nct.png")
create_boxplot(results.pooling.nct,"occurrence_InterquartileRange","pooling_OCCURRENCE_IQR_nct.png")
create_boxplot(results.pooling.nct,"occurrence_Minimum","pooling_OCCURRENCE_min_nct.png")
create_boxplot(results.pooling.nct,"occurrence_Maximum","pooling_OCCURRENCE_max_nct.png")
create_boxplot(results.pooling.nct,"occurrence_Range","pooling_OCCURRENCE_range_nct.png")





